import clsx from '@/libs/clsx';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--var-montserrat' });

export const metadata: Metadata = {
    title: 'Next App Test',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={montserrat.variable}>{children}</body>
        </html>
    );
}
